/*Colistor, collections and lists organizer
*Copyright (C) 2016  Colistor (Joel Favre)
*
*This program is free software: you can redistribute it and/or modify
*it under the terms of the GNU Affero General Public License as published
*by the Free Software Foundation, either version 3 of the License, or
*(at your option) any later version.
*
*This program is distributed in the hope that it will be useful,
*but WITHOUT ANY WARRANTY; without even the implied warranty of
*MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*GNU Affero General Public License for more details.
*
*You should have received a copy of the GNU Affero General Public License
*along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package com.colistor.core.persistence.model;

import com.colistor.core.persistence.dbaccess.Code;
import com.colistor.core.persistence.dbaccess.Field;
import com.colistor.core.persistence.dbaccess.PrimaryKey;
import jodd.vtor.constraint.NotBlank;

import java.util.Date;

public abstract class StandardObject {

    /**
     * The id of the object.
     * Is only used inside colistor-core.
     * The id is generated by the database
     * <p>
     * is_u = internal services on update
     * is_d = internal services on delete
     */
    @NotBlank(profiles = {"is_u,is_d"})
    @PrimaryKey(field = "id")
    public transient String id;

    /**
     * The code of the object.
     * May be exposed to the final user
     * The code is generated by the internal service.
     * <p>
     * s_u = services on update
     * s_d = services on delete
     */
    @NotBlank(profiles = {"s_u,s_d"})
    @Code(field = "code")
    public String code;

    /**
     * The date and time when the object has been created.
     * It is inserted by the internal service
     */
    @Field(name = "createdate", insert = true)
    public Date createDdate;

    /**
     * The date and time when the values of the object have been modified.
     * It is inserted/updated by the internal service
     */
    @Field(name = "updatedate", update = true)
    public Date updateDate;
}
